<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Crest</AssemblyName>
    <RootNamespace>Crest</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <None Include="..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>
