<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Crest.EFCore</AssemblyName>
    <RootNamespace>Crest.EFCore</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <ProjectReference Include="..\Crest\Crest.csproj" />
    <None Include="..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>
