<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>Crestful.Validation</PackageId>
    <AssemblyName>Crestful.Validation</AssemblyName>
    <RootNamespace>Crestful.Validation</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="FluentValidation" />
    <ProjectReference Include="..\Crestful\Crestful.csproj" />
    <None Include="..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>
