<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>Crestful.EFCore</PackageId>
    <AssemblyName>Crestful.EFCore</AssemblyName>
    <RootNamespace>Crestful.EFCore</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <ProjectReference Include="..\Crestful\Crestful.csproj" />
    <None Include="..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>
