namespace Crestful;

/// <summary>
/// Marker interface for resources that support optimistic concurrency control. When a resource
/// implements this interface and concurrency is enabled for the resource, the framework exposes the
/// value as an <c>ETag</c> response header, requires a matching <c>If-Match</c> header on updates and
/// deletes, and translates store-level concurrency failures into <c>412 Precondition Failed</c>.
/// </summary>
public interface IHasRowVersion
{
    /// <summary>
    /// The version token for this resource, normally generated by the store. With SQL Server,
    /// configure the property with <c>IsRowVersion()</c> so the database maintains it. Providers that
    /// do not generate row versions — EF Core's in-memory provider among them — need the value set
    /// explicitly; initialize it to an empty array to satisfy the required-property checks those
    /// providers apply.
    /// </summary>
    byte[] RowVersion { get; set; }
}